
source 'https://github.com/CocoaPods/Specs.git'

target 'DTContainerViewController_Example' do
  pod 'DTContainerViewController', :path => '../'

  target 'DTContainerViewController_Tests' do
    inherit! :search_paths


  end
end
